WITH AUDIENCE_TECHNOLOGY AS (

      
     select * from {{ 'DATAFLO_GOOGLEANALYTICS.AUDIENCE_TECHNOLOGY' }}  

)

select 
    ACCOUNT_ID	AS AUD_TECH_ACCOUNT_ID ,
    END_DATE	AS AUD_TECH_END_DATE ,
    GA_AVGSESSIONDURATION	AS AUD_TECH_GA_AVGSESSIONDURATION ,
    GA_BOUNCERATE	AS AUD_TECH_GA_BOUNCERATE ,
    GA_BROWSER	AS AUD_TECH_GA_BROWSER ,
    GA_DATE	AS AUD_TECH_GA_DATE ,
    GA_NEWUSERS	AS AUD_TECH_GA_NEWUSERS ,
    GA_OPERATINGSYSTEM	AS AUD_TECH_GA_OPERATINGSYSTEM ,
    GA_PAGEVIEWSPERSESSION	AS AUD_TECH_GA_PAGEVIEWSPERSESSION ,
    GA_SESSIONS	AS AUD_TECH_GA_SESSIONS ,
    GA_USERS	AS AUD_TECH_GA_USERS ,
    PROFILE_ID	AS AUD_TECH_PROFILE_ID ,
    START_DATE	AS AUD_TECH_START_DATE ,
    WEB_PROPERTY_ID AS AUD_TECH_WEB_PROPERTY_ID 

from AUDIENCE_TECHNOLOGY