WITH AUDIENCE_GEO_LOCATION AS (

      
     select * from {{ 'DATAFLO_GOOGLEANALYTICS.AUDIENCE_GEO_LOCATION' }}  

)

select 
ACCOUNT_ID AS AUD_GEOLOC_ACCOUNT_ID	
,END_DATE AS AUD_GEOLOC_END_DATE	
,GA_AVGSESSIONDURATION	AS AUD_GEOLOC_GA_AVGSESSIONDURATION
,GA_BOUNCERATE	AS AUD_GEOLOC_GA_BOUNCERATE
,GA_CITY AS AUD_GEOLOC_GA_CITY	
,GA_CONTINENT AS AUD_GEOLOC_GA_CONTINENT	
,GA_COUNTRY	AS AUD_GEOLOC_GA_COUNTRY
,GA_DATE AS AUD_GEOLOC_GA_DATE	
,GA_NEWUSERS AS AUD_GEOLOC_GA_NEWUSERS	
,GA_PAGEVIEWSPERSESSION	AS AUD_GEOLOC_GA_PAGEVIEWSPERSESSION
,GA_SESSIONS AS AUD_GEOLOC_GA_SESSIONS
,GA_SUBCONTINENT AS AUD_GEOLOC_GA_SUBCONTINENT	
,GA_USERS	AS AUD_GEOLOC_GA_USERS
,PROFILE_ID	AS AUD_GEOLOC_PROFILE_ID
,START_DATE	AS AUD_GEOLOC_START_DATE
,WEB_PROPERTY_ID AS AUD_GEOLOC_WEB_PROPERTY_ID

from AUDIENCE_GEO_LOCATION
