version: 2

models:

  - name: stg_sf_account
    columns:
      - name: account_id
        tests: 
          - not_null
          - unique

  - name: stg_sf_opportunity
    columns:
      - name: opportunity_id
        tests: 
          - not_null
          - unique

  - name: stg_sf_user
    columns:
      - name: user_id
        tests: 
          - not_null
          - unique

  - name: stg_sf_user_role
    columns:
      - name: user_role_id
        tests: 
          - not_null
          - unique

  - name: stg_sf_contact
    columns:
      - name: contact_id
        tests: 
          - not_null
          - unique
 
  - name: stg_sf_lead
    columns:
     - name: lead_id
       tests: 
          - not_null
          - unique


